### ISSUE TITLE
How to seek / set the current time?

### ISSUE THREAD

**Issue by busychild** [bdunn44/MEJS-Vaadin#1]
Hi there,
we need the ability to set the current time (seek) for the media component. I've found the method "mediaComponent.setCurrentTime()" but this method doesn't allow me to pass a parameter to it.
Could you give me a hint?
Thanks in advance and best regards

**Comment by bdunn44** [comment]
Good catch! You should be able to pass an integer value in that method. I've added that in version 1.1.4 which I just released.

Note that seeking doesn't work at all in Chrome - I need to investigate why but it seems to be a problem with MediaElement.js itself.

-Bryson

**Comment by busychild** [comment]
Awesome - thanks a lot! I'll give it a try!

**Comment by busychild** [comment]
Hi Bryson,
the setCurrentTime() method seems to work properly but i found another issue. The getCurrentTime() method always return 0 (tested in Safari). I've added an "addSeekedListener" and also tried to get the time after the metadata is loaded but the result stays the same.
Have you got an idea?

btw: The reason why we need these method is that we are developing an web application where user a is able to control the video player of user b.

Thanks in advance!

**Comment by bdunn44** [comment]
I see what you mean... I'll need to do some debugging, the problem isn't obvious to me. I should have some time to look at it today.

**Comment by bdunn44** [comment]
Looked into this one... It's a pretty big bug. All of the player state attributes like paused, current time, volume, etc. aren't being set correctly. I've asked Stack Overflow for help - not sure what's wrong. [http://stackoverflow.com/questions/26171989/access-mediaelement-js-player-attributes]

**Comment by bdunn44** [comment]
Could you check out the newest release and let me know if that solves your problem? I fixed the player state issues.

**Comment by busychild** [comment]
Hi Bryson,
the methods seem to be working fine now but unfortunately i'm facing some other problems:
1. In Firefox the player add's something like an debug overlay to the player
2. If i add an .ogg file as the source the player returns the url "http://localhost:8181/nothing" instead of the correct url (e.g. "http://localhost:8181/media/example.ogg")

I'm currently testing the player at different browsers and operating systems and will keep you updated. Could you please add the source files for the 1.2.0 version to the git repository? It makes debugging much easier ;)

Thanks in advance and best regards

Florian

**Comment by bdunn44** [comment]
Thanks for the feedback Florian - I've noticed that too. I've synced the version 1.2.0 changes and will check out the bugs you mentioned.

-Bryson

**Comment by bdunn44** [comment]
What version of Firefox did you see this on? It looks good in 32.0.3 but it doesn't work at all in IE 9. No idea why... When I open the JS console the players show up but IE crashes.

**Comment by busychild** [comment]
I'm on a mac using Firefox 33.0. The issue with the debug overlay was just a setting in the mediacomponent-conntector.js file ("var debugMode = false") but the problem with setting the source still exists. 

It seems the the "setSource" method doesn't replace the src values from the template in the mejslibrary.js file (var videoElement = ...) correctly. It has nothing to with the file typ as neither mp4 nor ogg files are working on firefox (there's no problem on safari or chrome). I'll try to investigate the problem a little bit deeper today.

Best regards
Florian

**Comment by bdunn44** [comment]
Interesting, I added that debug overlay but it didn't do anything in my browsers :) In the latest release (1.2.1) I made sure debug is off. 

I also tested the latest version in Firefox and .mp3, .mp4 and .ogg files work without issue. Try upgrading to 1.2.1 and be sure to clear your browsers cache. If the issue still persists please send code and I'll try to reproduce the bug.

Thanks,
Bryson

**Comment by bdunn44** [comment]
Closing due to inactivity
